// SAT Math Question Bank
// 100+ questions covering all Digital SAT Math topics
// Topics: Algebra, Advanced Math, Problem Solving & Data Analysis, Geometry & Trig

window.SAT_QUESTIONS = [

// ============================================
// ALGEBRA - Linear Equations (12 questions)
// ============================================
{id:"alg-lin-001",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:1,type:"mc",question:"If $3x + 7 = 22$, what is the value of $x$?",choices:["3","5","7","10"],correctAnswer:1,explanation:"Subtract 7 from both sides: $3x = 15$.\nDivide both sides by 3: $x = 5$.",strategy:"Isolate the variable using inverse operations. Undo addition first, then multiplication.",commonMistake:"Dividing before subtracting, or forgetting to do the same operation to both sides."},
{id:"alg-lin-002",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:1,type:"mc",question:"What is the solution to $5x - 3 = 2x + 9$?",choices:["2","3","4","6"],correctAnswer:2,explanation:"Get all x terms on one side: $5x - 2x = 9 + 3$.\n$3x = 12$, so $x = 4$.",strategy:"Move variable terms to one side and constants to the other.",commonMistake:"Sign errors when moving terms across the equals sign."},
{id:"alg-lin-003",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:2,type:"mc",question:"If $\\frac{2x+1}{3} = 5$, what is $x$?",choices:["6","7","8","9"],correctAnswer:1,explanation:"Multiply both sides by 3: $2x + 1 = 15$.\nSubtract 1: $2x = 14$.\nDivide by 2: $x = 7$.",strategy:"Clear fractions first by multiplying both sides by the denominator.",commonMistake:"Forgetting to multiply the entire numerator by 3."},
{id:"alg-lin-004",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:2,type:"grid-in",question:"If $4(x - 2) + 3 = 19$, what is the value of $x$?",correctAnswer:6,explanation:"Distribute: $4x - 8 + 3 = 19$.\nCombine: $4x - 5 = 19$.\nAdd 5: $4x = 24$.\nDivide: $x = 6$.",strategy:"Distribute first, then combine like terms, then isolate x.",commonMistake:"Forgetting to distribute to the negative 2."},
{id:"alg-lin-005",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:2,type:"mc",question:"If $2(3x + 4) = 5x + 13$, what is $x$?",choices:["3","5","7","9"],correctAnswer:1,explanation:"Distribute: $6x + 8 = 5x + 13$.\nSubtract 5x: $x + 8 = 13$.\nSubtract 8: $x = 5$.",strategy:"Distribute first, then collect variable terms on one side.",commonMistake:"Not distributing the 2 to both terms."},
{id:"alg-lin-006",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:3,type:"mc",question:"If $\\frac{x}{3} + \\frac{x}{4} = 7$, what is $x$?",choices:["10","12","14","16"],correctAnswer:1,explanation:"Find common denominator (12): $\\frac{4x}{12} + \\frac{3x}{12} = 7$.\nCombine: $\\frac{7x}{12} = 7$.\nMultiply by 12: $7x = 84$, so $x = 12$.",strategy:"When you see fractions with different denominators, multiply everything by the LCD.",commonMistake:"Using wrong common denominator or combining fractions incorrectly."},
{id:"alg-lin-007",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:3,type:"grid-in",question:"A phone plan charges $30 per month plus $0.10 per text message. If the total bill is $52, how many text messages were sent?",correctAnswer:220,explanation:"Set up: $30 + 0.10t = 52$.\nSubtract 30: $0.10t = 22$.\nDivide by 0.10: $t = 220$.",strategy:"Translate word problems: fixed cost + (rate)(quantity) = total.",commonMistake:"Forgetting the decimal in 0.10."},
{id:"alg-lin-008",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:3,type:"mc",question:"If $3(2x - 1) - 2(x + 4) = 13$, what is $x$?",choices:["4","5","6","7"],correctAnswer:2,explanation:"Distribute: $6x - 3 - 2x - 8 = 13$.\nCombine like terms: $4x - 11 = 13$.\nAdd 11: $4x = 24$.\nDivide by 4: $x = 6$.",strategy:"Be very careful with distributing negatives.",commonMistake:"Distributing -2 only to x and not to +4."},
{id:"alg-lin-009",topic:"algebra",subtopic:"linear-equations",title:"Linear Equations",difficulty:4,type:"mc",question:"If $\\frac{2x+3}{5} = \\frac{x-1}{3}$, what is the value of $x$?",choices:["$-8$","$-14$","$8$","$14$"],correctAnswer:1,explanation:"Cross multiply: $3(2x+3) = 5(x-1)$.\n$6x + 9 = 5x - 5$.\n$x = -14$.",strategy:"When fraction = fraction, cross-multiply to clear both denominators.",commonMistake:"Cross-multiplying incorrectly or not distributing properly."},

// ============================================
// ALGEBRA - Linear Functions & Graphs (8 questions)
// ============================================
{id:"alg-lf-001",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:1,type:"mc",question:"What is the slope of the line $y = 3x + 7$?",choices:["3","7","$\\frac{1}{3}$","$-3$"],correctAnswer:0,explanation:"In slope-intercept form $y = mx + b$, the slope is $m$. Here $m = 3$.",strategy:"In y = mx + b, m is always the slope and b is the y-intercept.",commonMistake:"Confusing slope with y-intercept."},
{id:"alg-lf-002",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:2,type:"mc",question:"What is the slope of the line passing through $(2, 5)$ and $(6, 13)$?",choices:["$\\frac{1}{2}$","2","4","8"],correctAnswer:1,explanation:"Slope $= \\frac{y_2 - y_1}{x_2 - x_1} = \\frac{13 - 5}{6 - 2} = \\frac{8}{4} = 2$.",strategy:"Slope = rise over run = change in y / change in x.",commonMistake:"Putting x-values in the numerator instead of y-values."},
{id:"alg-lf-003",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:2,type:"mc",question:"A line has slope 4 and passes through $(1, 3)$. What is the y-intercept?",choices:["$-1$","$0$","$1$","$3$"],correctAnswer:0,explanation:"Use $y = mx + b$: $3 = 4(1) + b$.\n$3 = 4 + b$, so $b = -1$.",strategy:"Plug the known point and slope into y = mx + b and solve for b.",commonMistake:"Plugging values into the wrong places."},
{id:"alg-lf-004",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:2,type:"mc",question:"A car rental charges a flat fee of $25 plus $0.15 per mile. Which equation represents total cost $C$ for $m$ miles?",choices:["$C = 0.15m + 25$","$C = 25m + 0.15$","$C = 0.15m - 25$","$C = 25m + 15$"],correctAnswer:0,explanation:"Flat fee ($25) is the y-intercept. Per-mile rate ($0.15) is the slope. So $C = 0.15m + 25$.",strategy:"In context: slope = rate of change (per unit), y-intercept = starting/fixed value.",commonMistake:"Mixing up which number is the rate vs. the fixed cost."},
{id:"alg-lf-005",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:3,type:"mc",question:"Line $A$: $y = 2x + 3$. Line $B$ is perpendicular to $A$ and passes through the origin. What is Line $B$'s equation?",choices:["$y = 2x$","$y = -2x$","$y = -\\frac{1}{2}x$","$y = \\frac{1}{2}x$"],correctAnswer:2,explanation:"Perpendicular slopes are negative reciprocals.\nSlope of A = 2, so slope of B = $-\\frac{1}{2}$.\nThrough origin: $b = 0$. So $y = -\\frac{1}{2}x$.",strategy:"Perpendicular: flip fraction and change sign. Slopes multiply to -1.",commonMistake:"Only flipping the fraction without changing the sign."},
{id:"alg-lf-006",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:3,type:"grid-in",question:"In the equation $y = -3x + 18$, at what value of $x$ does the line cross the x-axis?",correctAnswer:6,explanation:"X-intercept: set $y = 0$.\n$0 = -3x + 18$.\n$3x = 18$, so $x = 6$.",strategy:"X-intercept means y = 0. Set y = 0 and solve for x.",commonMistake:"Confusing x-intercept (set y=0) with y-intercept (set x=0)."},
{id:"alg-lf-007",topic:"algebra",subtopic:"linear-functions",title:"Linear Functions",difficulty:2,type:"mc",question:"Which line is parallel to $y = -2x + 5$?",choices:["$y = 2x + 1$","$y = -2x - 3$","$y = \\frac{1}{2}x + 5$","$y = -\\frac{1}{2}x + 5$"],correctAnswer:1,explanation:"Parallel lines have the same slope. Slope of original = $-2$. $y = -2x - 3$ also has slope $-2$.",strategy:"Parallel = same slope, different y-intercept.",commonMistake:"Thinking parallel means same y-intercept instead of same slope."},

// ============================================
// ALGEBRA - Systems of Equations (7 questions)
// ============================================
{id:"alg-sys-001",topic:"algebra",subtopic:"systems",title:"Systems of Equations",difficulty:2,type:"mc",question:"What is the solution to: $x + y = 10$ and $x - y = 4$?",choices:["$(7, 3)$","$(6, 4)$","$(8, 2)$","$(5, 5)$"],correctAnswer:0,explanation:"Add the equations: $2x = 14$, so $x = 7$.\nSubstitute: $7 + y = 10$, so $y = 3$.",strategy:"When one equation has +y and other has -y, add them to eliminate y.",commonMistake:"Subtracting when you should add."},
{id:"alg-sys-002",topic:"algebra",subtopic:"systems",title:"Systems of Equations",difficulty:2,type:"mc",question:"If $2x + 3y = 12$ and $x = 3$, what is $y$?",choices:["1","2","3","4"],correctAnswer:1,explanation:"Substitute: $2(3) + 3y = 12$.\n$6 + 3y = 12$, so $3y = 6$, $y = 2$.",strategy:"When one variable is given, substitute directly.",commonMistake:"Arithmetic errors when substituting."},
{id:"alg-sys-003",topic:"algebra",subtopic:"systems",title:"Systems of Equations",difficulty:3,type:"mc",question:"The system $3x + 2y = 16$ and $x + 2y = 8$ has solution:",choices:["$(4, 2)$","$(2, 4)$","$(3, 3.5)$","$(6, -1)$"],correctAnswer:0,explanation:"Subtract second from first: $2x = 8$, so $x = 4$.\nSubstitute: $4 + 2y = 8$, $y = 2$.",strategy:"When both equations have same coefficient on one variable, subtract to eliminate.",commonMistake:"Sign errors when subtracting equations."},
{id:"alg-sys-004",topic:"algebra",subtopic:"systems",title:"Systems of Equations",difficulty:3,type:"grid-in",question:"A store sells apples for $2 each and bananas for $1 each. Sam buys 8 fruits for $11. How many apples?",correctAnswer:3,explanation:"$a + b = 8$ and $2a + b = 11$.\nSubtract: $a = 3$.",strategy:"Set up two equations from two pieces of info, then eliminate.",commonMistake:"Setting up only one equation."},
{id:"alg-sys-005",topic:"algebra",subtopic:"systems",title:"Systems of Equations",difficulty:4,type:"mc",question:"For what value of $k$ does $2x + 3y = 6$ and $4x + 6y = k$ have infinitely many solutions?",choices:["6","12","18","24"],correctAnswer:1,explanation:"Infinitely many solutions = same line. Multiply first by 2: $4x + 6y = 12$. So $k = 12$.",strategy:"Infinite solutions: one equation is a multiple of the other.",commonMistake:"Confusing infinite solutions (same line) with no solutions (parallel)."},
{id:"alg-sys-006",topic:"algebra",subtopic:"systems",title:"Systems of Equations",difficulty:3,type:"mc",question:"At a theater, 2 adult and 3 child tickets cost $36. One adult and 2 child tickets cost $20. What is the adult ticket price?",choices:["$8","$10","$12","$14"],correctAnswer:2,explanation:"$2a + 3c = 36$ and $a + 2c = 20$.\nMultiply second by 2: $2a + 4c = 40$.\nSubtract first: $c = 4$.\n$a = 20 - 8 = 12$.",strategy:"Elimination works great when you can match coefficients easily.",commonMistake:"Subtracting in the wrong order."},

// ============================================
// ALGEBRA - Inequalities (4 questions)
// ============================================
{id:"alg-ineq-001",topic:"algebra",subtopic:"inequalities",title:"Linear Inequalities",difficulty:2,type:"mc",question:"If $3x - 5 > 7$, which describes all solutions?",choices:["$x > 4$","$x > 2$","$x < 4$","$x > 12$"],correctAnswer:0,explanation:"Add 5: $3x > 12$. Divide by 3: $x > 4$.",strategy:"Solve like equations. Only flip sign when multiplying/dividing by negative.",commonMistake:"Flipping the inequality sign unnecessarily."},
{id:"alg-ineq-002",topic:"algebra",subtopic:"inequalities",title:"Linear Inequalities",difficulty:2,type:"mc",question:"If $-2x + 1 \\geq 7$, what is the solution?",choices:["$x \\geq 3$","$x \\leq 3$","$x \\geq -3$","$x \\leq -3$"],correctAnswer:3,explanation:"Subtract 1: $-2x \\geq 6$.\nDivide by $-2$ (FLIP the sign!): $x \\leq -3$.",strategy:"CRITICAL: Multiply or divide by negative = FLIP the inequality sign.",commonMistake:"Forgetting to flip when dividing by -2."},
{id:"alg-ineq-003",topic:"algebra",subtopic:"inequalities",title:"Linear Inequalities",difficulty:3,type:"mc",question:"A student scored 72, 85, and 78 on three tests. What minimum 4th test score gives an average of at least 80?",choices:["80","83","85","88"],correctAnswer:2,explanation:"$\\frac{72 + 85 + 78 + x}{4} \\geq 80$.\n$235 + x \\geq 320$.\n$x \\geq 85$.",strategy:"Average problems: multiply both sides by count to clear the fraction.",commonMistake:"Forgetting to multiply by 4."},
{id:"alg-ineq-004",topic:"algebra",subtopic:"inequalities",title:"Linear Inequalities",difficulty:3,type:"mc",question:"Which represents 'a number $n$ is at least 5 more than twice $m$'?",choices:["$n \\geq 2m + 5$","$n > 2m + 5$","$n \\leq 2m + 5$","$n = 2m + 5$"],correctAnswer:0,explanation:"'At least' means $\\geq$. '5 more than twice m' means $2m + 5$. So $n \\geq 2m + 5$.",strategy:"Translations: 'at least' = >=, 'at most' = <=, 'more than' = >, 'fewer than' = <.",commonMistake:"Using > instead of >= for 'at least'."},

// ============================================
// ALGEBRA - Absolute Value (2 questions)
// ============================================
{id:"alg-abs-001",topic:"algebra",subtopic:"absolute-value",title:"Absolute Value",difficulty:3,type:"mc",question:"What are the solutions to $|x - 4| = 7$?",choices:["$x = 3$ only","$x = 11$ only","$x = -3$ and $x = 11$","$x = 3$ and $x = -11$"],correctAnswer:2,explanation:"$x - 4 = 7$ gives $x = 11$.\n$x - 4 = -7$ gives $x = -3$.\nSolutions: $x = -3$ and $x = 11$.",strategy:"$|A| = k$ gives TWO equations: $A = k$ and $A = -k$.",commonMistake:"Only finding one solution instead of two."},
{id:"alg-abs-002",topic:"algebra",subtopic:"absolute-value",title:"Absolute Value",difficulty:3,type:"mc",question:"How many solutions does $|2x + 1| = -3$ have?",choices:["0","1","2","Infinite"],correctAnswer:0,explanation:"Absolute value is always $\\geq 0$. It can never equal a negative number. No solutions.",strategy:"If |something| = negative number, answer is ZERO solutions. Always.",commonMistake:"Trying to solve anyway and getting false solutions."},

// ============================================
// ALGEBRA - Word Problems (5 questions)
// ============================================
{id:"alg-wp-001",topic:"algebra",subtopic:"word-problems",title:"Algebraic Word Problems",difficulty:2,type:"mc",question:"Tom is 3 years older than twice Sara's age. If Tom is 17, how old is Sara?",choices:["5","7","10","14"],correctAnswer:1,explanation:"$17 = 2s + 3$.\n$14 = 2s$, so $s = 7$.",strategy:"Translate: 'older than' = add, 'twice' = multiply by 2.",commonMistake:"Writing the equation backwards."},
{id:"alg-wp-002",topic:"algebra",subtopic:"word-problems",title:"Algebraic Word Problems",difficulty:2,type:"grid-in",question:"A rectangle has perimeter 36 cm. Length is 4 cm more than width. What is the width in cm?",correctAnswer:7,explanation:"$2(w+4+w) = 36$.\n$2(2w+4) = 36$.\n$4w+8=36$.\n$4w=28$, $w=7$.",strategy:"Perimeter = 2l + 2w. Set up two equations from the info given.",commonMistake:"Using P = l + w instead of P = 2l + 2w."},
{id:"alg-wp-003",topic:"algebra",subtopic:"word-problems",title:"Algebraic Word Problems",difficulty:3,type:"mc",question:"Two trains leave the same station traveling in opposite directions at 60 mph and 80 mph. After how many hours are they 420 miles apart?",choices:["2","2.5","3","3.5"],correctAnswer:2,explanation:"Combined rate: $60 + 80 = 140$ mph.\n$420 = 140t$, so $t = 3$ hours.",strategy:"Opposite directions: add speeds for combined rate.",commonMistake:"Using only one train's speed."},
{id:"alg-wp-004",topic:"algebra",subtopic:"word-problems",title:"Algebraic Word Problems",difficulty:3,type:"grid-in",question:"A garage charges $5 for the first hour and $3 each additional hour. Maria paid $23. How many total hours?",correctAnswer:7,explanation:"First hour: $5. Remaining: $23-$5=$18.\nAdditional hours: $18/$3=6.\nTotal: 1+6=7.",strategy:"Break into fixed part and variable part.",commonMistake:"Dividing total by rate, forgetting the different first-hour price."},
{id:"alg-wp-005",topic:"algebra",subtopic:"word-problems",title:"Algebraic Word Problems",difficulty:3,type:"mc",question:"The sum of three consecutive integers is 84. What is the largest?",choices:["27","28","29","30"],correctAnswer:2,explanation:"$n + (n+1) + (n+2) = 84$.\n$3n + 3 = 84$, $3n = 81$, $n = 27$.\nLargest = $29$.",strategy:"Consecutive integers: n, n+1, n+2.",commonMistake:"Giving the middle or smallest instead of the largest."},

// ============================================
// ADVANCED MATH - Quadratics (8 questions)
// ============================================
{id:"am-quad-001",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:2,type:"mc",question:"What are the solutions to $x^2 - 5x + 6 = 0$?",choices:["$x=2$ and $x=3$","$x=-2$ and $x=-3$","$x=1$ and $x=6$","$x=-1$ and $x=-6$"],correctAnswer:0,explanation:"Factor: $(x-2)(x-3)=0$.\n$x=2$ or $x=3$.",strategy:"Find two numbers that multiply to c and add to b.",commonMistake:"Getting the signs wrong when factoring."},
{id:"am-quad-002",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:2,type:"mc",question:"What are the solutions to $x^2 + 4x - 12 = 0$?",choices:["$x=2, x=-6$","$x=-2, x=6$","$x=3, x=-4$","$x=-3, x=4$"],correctAnswer:0,explanation:"Factor: $(x+6)(x-2) = 0$.\n$x=-6$ or $x=2$.\nCheck: $6 \\times (-2) = -12$ and $6+(-2) = 4$.",strategy:"Need numbers that multiply to -12 and add to +4: that is +6 and -2.",commonMistake:"Getting signs wrong. Multiply to c, ADD to b."},
{id:"am-quad-003",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:3,type:"mc",question:"Using the quadratic formula, solve $2x^2 + 5x - 3 = 0$.",choices:["$x=\\frac{1}{2}$ and $x=-3$","$x=-\\frac{1}{2}$ and $x=3$","$x=1$ and $x=-\\frac{3}{2}$","$x=-1$ and $x=\\frac{3}{2}$"],correctAnswer:0,explanation:"$a=2, b=5, c=-3$.\n$x = \\frac{-5 \\pm \\sqrt{25+24}}{4} = \\frac{-5 \\pm 7}{4}$.\n$x = \\frac{2}{4} = \\frac{1}{2}$ or $x = \\frac{-12}{4} = -3$.",strategy:"Quadratic formula: $x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}$. Memorize it!",commonMistake:"Forgetting 2a in the denominator (not just a)."},
{id:"am-quad-004",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:3,type:"mc",question:"What is the vertex of $y = (x-3)^2 + 5$?",choices:["$(3,5)$","$(-3,5)$","$(3,-5)$","$(-3,-5)$"],correctAnswer:0,explanation:"Vertex form: $y = a(x-h)^2 + k$. Vertex = $(h,k) = (3,5)$.",strategy:"Vertex form: vertex is $(h,k)$. Note the sign change on h!",commonMistake:"Writing $(-3,5)$ by not accounting for the minus in $(x-h)$."},
{id:"am-quad-005",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:3,type:"mc",question:"For $x^2 - 6x + k = 0$ to have exactly one solution, $k$ must equal:",choices:["6","9","12","36"],correctAnswer:1,explanation:"One solution: discriminant = 0.\n$b^2-4ac=0$: $36-4k=0$, so $k=9$.",strategy:"Discriminant: positive = 2 solutions, zero = 1, negative = 0 real solutions.",commonMistake:"Confusing one solution with no solutions."},
{id:"am-quad-006",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:4,type:"grid-in",question:"If $x^2 - 8x + 12 = 0$, what is the sum of the solutions?",correctAnswer:8,explanation:"By Vieta's: sum of roots = $-b/a = 8$.\nOr factor: $(x-2)(x-6)=0$, roots 2 and 6, sum = 8.",strategy:"Sum of roots of $ax^2+bx+c=0$ is $-b/a$.",commonMistake:"Multiplying instead of adding the roots."},
{id:"am-quad-007",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:2,type:"mc",question:"Which equals $(x+4)^2$?",choices:["$x^2+16$","$x^2+4x+16$","$x^2+8x+16$","$2x+8$"],correctAnswer:2,explanation:"$(x+4)^2 = x^2 + 2(x)(4) + 16 = x^2+8x+16$.",strategy:"$(a+b)^2 = a^2+2ab+b^2$. Don't forget the middle term!",commonMistake:"Writing $x^2+16$ and forgetting the middle term $8x$."},
{id:"am-quad-008",topic:"advanced-math",subtopic:"quadratics",title:"Quadratic Equations",difficulty:3,type:"mc",question:"A ball follows $h=-16t^2+64t+5$. What is the max height?",choices:["64 ft","69 ft","73 ft","133 ft"],correctAnswer:1,explanation:"Max at $t = -b/(2a) = -64/(2 \\cdot -16) = 2$.\n$h(2) = -64+128+5 = 69$ ft.",strategy:"For $ax^2+bx+c$, vertex at $x=-b/(2a)$.",commonMistake:"Computing t correctly but substituting wrong."},

// ============================================
// ADVANCED MATH - Exponents & Polynomials (7 questions)
// ============================================
{id:"am-exp-001",topic:"advanced-math",subtopic:"exponents",title:"Exponents & Polynomials",difficulty:1,type:"mc",question:"Simplify: $x^3 \\cdot x^4$",choices:["$x^7$","$x^{12}$","$x^1$","$7x$"],correctAnswer:0,explanation:"Multiply same bases: add exponents. $x^{3+4} = x^7$.",strategy:"Product rule: $x^a \\cdot x^b = x^{a+b}$.",commonMistake:"Multiplying exponents instead of adding."},
{id:"am-exp-002",topic:"advanced-math",subtopic:"exponents",title:"Exponents & Polynomials",difficulty:2,type:"mc",question:"Simplify: $\\frac{x^8}{x^3}$",choices:["$x^5$","$x^{11}$","$x^{24}$","$x^{8/3}$"],correctAnswer:0,explanation:"Divide same bases: subtract exponents. $x^{8-3} = x^5$.",strategy:"Quotient rule: $x^a/x^b = x^{a-b}$.",commonMistake:"Adding exponents instead of subtracting when dividing."},
{id:"am-exp-003",topic:"advanced-math",subtopic:"exponents",title:"Exponents & Polynomials",difficulty:2,type:"mc",question:"What is $(2x^3)^2$?",choices:["$2x^6$","$4x^6$","$4x^5$","$2x^5$"],correctAnswer:1,explanation:"$2^2 \\cdot (x^3)^2 = 4x^6$.",strategy:"Power rule: $(ab)^n = a^n b^n$ and $(x^a)^b = x^{ab}$.",commonMistake:"Forgetting to square the coefficient 2."},
{id:"am-exp-004",topic:"advanced-math",subtopic:"exponents",title:"Exponents & Polynomials",difficulty:2,type:"mc",question:"What is $5^0$?",choices:["0","1","5","Undefined"],correctAnswer:1,explanation:"Any nonzero number to the power 0 equals 1.",strategy:"$a^0 = 1$ for any $a \\neq 0$.",commonMistake:"Thinking $5^0 = 0$."},
{id:"am-exp-005",topic:"advanced-math",subtopic:"exponents",title:"Exponents & Polynomials",difficulty:3,type:"mc",question:"Simplify: $(x+3)(x-5)$",choices:["$x^2-2x-15$","$x^2+2x-15$","$x^2-8x-15$","$x^2-2x+15$"],correctAnswer:0,explanation:"FOIL: $x^2-5x+3x-15 = x^2-2x-15$.",strategy:"FOIL: First, Outer, Inner, Last. Then combine like terms.",commonMistake:"Sign errors with negative terms."},
{id:"am-exp-006",topic:"advanced-math",subtopic:"exponents",title:"Exponents & Polynomials",difficulty:3,type:"mc",question:"Simplify: $\\frac{12x^5y^3}{4x^2y}$",choices:["$3x^3y^2$","$3x^7y^4$","$8x^3y^2$","$3x^{2.5}y^3$"],correctAnswer:0,explanation:"$12/4=3$, $x^{5-2}=x^3$, $y^{3-1}=y^2$.\nResult: $3x^3y^2$.",strategy:"Divide coefficients, subtract exponents for same bases.",commonMistake:"Adding exponents when dividing."},

// ============================================
// ADVANCED MATH - Functions (6 questions)
// ============================================
{id:"am-func-001",topic:"advanced-math",subtopic:"functions",title:"Functions",difficulty:2,type:"mc",question:"If $f(x) = 2x^2 - 3x + 1$, what is $f(3)$?",choices:["8","10","14","16"],correctAnswer:1,explanation:"$f(3) = 2(9)-3(3)+1 = 18-9+1 = 10$.",strategy:"Replace every x with the given value and compute carefully.",commonMistake:"Forgetting order of operations."},
{id:"am-func-002",topic:"advanced-math",subtopic:"functions",title:"Functions",difficulty:2,type:"mc",question:"If $f(x)=x+3$ and $g(x)=2x$, what is $f(g(4))$?",choices:["7","8","11","14"],correctAnswer:2,explanation:"$g(4)=8$. Then $f(8)=11$.",strategy:"Composition: work inside out. Compute g first, then plug into f.",commonMistake:"Computing f first instead of g."},
{id:"am-func-003",topic:"advanced-math",subtopic:"functions",title:"Functions",difficulty:3,type:"mc",question:"If $f(x)=\\frac{x+2}{x-1}$, which $x$ is NOT in the domain?",choices:["$-2$","$0$","$1$","$2$"],correctAnswer:2,explanation:"Denominator = 0 when $x=1$. So $x=1$ is excluded.",strategy:"For fractions, set denominator = 0 to find excluded values.",commonMistake:"Setting numerator to zero instead."},
{id:"am-func-004",topic:"advanced-math",subtopic:"functions",title:"Functions",difficulty:3,type:"grid-in",question:"If $f(x) = 3x - 7$ and $f(a) = 11$, what is $a$?",correctAnswer:6,explanation:"$3a - 7 = 11$, $3a = 18$, $a = 6$.",strategy:"Set function equal to output and solve for input.",commonMistake:"Plugging 11 in for x instead of setting f(a) = 11."},
{id:"am-func-005",topic:"advanced-math",subtopic:"functions",title:"Functions",difficulty:4,type:"mc",question:"If $f(x)=2x-3$ and $f(a+1)=13$, what is $a$?",choices:["5","7","8","9"],correctAnswer:1,explanation:"$2(a+1)-3=13$.\n$2a+2-3=13$.\n$2a-1=13$, $2a=14$, $a=7$.",strategy:"Replace x with the entire expression, then solve.",commonMistake:"Only replacing x with a, forgetting +1."},
{id:"am-func-006",topic:"advanced-math",subtopic:"functions",title:"Functions",difficulty:3,type:"mc",question:"If $f(x)=x^2+1$ and $g(x)=x-3$, what is $f(g(5))$?",choices:["3","5","23","26"],correctAnswer:1,explanation:"$g(5)=2$. $f(2)=4+1=5$.",strategy:"Inside out: g first, then f.",commonMistake:"Computing f(5) first."},

// ============================================
// ADVANCED MATH - Exponential & Radical (4 questions)
// ============================================
{id:"am-expn-001",topic:"advanced-math",subtopic:"exponential",title:"Exponential & Radical Expressions",difficulty:3,type:"mc",question:"Bacteria double every 3 hours. Starting with 100, how many after 9 hours?",choices:["300","400","600","800"],correctAnswer:3,explanation:"9 hours = 3 doublings. $100 \\times 2^3 = 800$.",strategy:"For doubling: multiply by $2^{\\text{periods}}$.",commonMistake:"Adding instead of multiplying."},
{id:"am-expn-002",topic:"advanced-math",subtopic:"exponential",title:"Exponential & Radical Expressions",difficulty:3,type:"mc",question:"Simplify: $\\sqrt{75}$",choices:["$3\\sqrt{5}$","$5\\sqrt{3}$","$15$","$25\\sqrt{3}$"],correctAnswer:1,explanation:"$\\sqrt{75}=\\sqrt{25 \\cdot 3}=5\\sqrt{3}$.",strategy:"Factor out the largest perfect square under the radical.",commonMistake:"Using 9 instead of 25 as the perfect square factor."},
{id:"am-expn-003",topic:"advanced-math",subtopic:"exponential",title:"Exponential & Radical Expressions",difficulty:4,type:"mc",question:"Which equals $x^{2/3}$?",choices:["$\\sqrt[3]{x^2}$","$\\sqrt{x^3}$","$\\frac{x^2}{3}$","$(\\sqrt{x})^3$"],correctAnswer:0,explanation:"$x^{a/b} = \\sqrt[b]{x^a}$. So $x^{2/3} = \\sqrt[3]{x^2}$.",strategy:"Fractional exponents: numerator = power, denominator = root.",commonMistake:"Confusing which is root and which is power."},
{id:"am-expn-004",topic:"advanced-math",subtopic:"exponential",title:"Exponential & Radical Expressions",difficulty:3,type:"mc",question:"A car loses 15% value yearly. Worth $20,000 now. Value in 3 years?",choices:["$11,000","$12,283","$14,450","$17,000"],correctAnswer:1,explanation:"$20000 \\times (0.85)^3 = 20000 \\times 0.614 \\approx 12,283$.",strategy:"Decay: $\\text{value} = \\text{initial} \\times (1-r)^t$.",commonMistake:"Subtracting 15% three times separately instead of multiplying."},

// ============================================
// PROBLEM SOLVING - Ratios & Proportions (5 questions)
// ============================================
{id:"ps-rat-001",topic:"problem-solving",subtopic:"ratios",title:"Ratios & Proportions",difficulty:1,type:"mc",question:"Boys to girls ratio is 3:5 and there are 15 girls. How many boys?",choices:["5","9","12","25"],correctAnswer:1,explanation:"$\\frac{3}{5}=\\frac{b}{15}$. Cross multiply: $5b=45$, $b=9$.",strategy:"Set up proportion, then cross-multiply.",commonMistake:"Setting up the proportion backwards."},
{id:"ps-rat-002",topic:"problem-solving",subtopic:"ratios",title:"Ratios & Proportions",difficulty:2,type:"mc",question:"Recipe: 2 cups flour per 3 cups sugar. Using 9 cups sugar, how much flour?",choices:["4","5","6","8"],correctAnswer:2,explanation:"$\\frac{2}{3}=\\frac{f}{9}$. $3f=18$, $f=6$.",strategy:"Cross-multiplication: $\\frac{a}{b}=\\frac{c}{d}$ means $ad=bc$.",commonMistake:"Multiplying instead of cross-multiplying."},
{id:"ps-rat-003",topic:"problem-solving",subtopic:"ratios",title:"Ratios & Proportions",difficulty:2,type:"grid-in",question:"A car travels 180 miles in 3 hours. Speed in mph?",correctAnswer:60,explanation:"Speed = distance/time = 180/3 = 60 mph.",strategy:"Rate = amount / time.",commonMistake:"Multiplying instead of dividing."},
{id:"ps-rat-004",topic:"problem-solving",subtopic:"ratios",title:"Ratios & Proportions",difficulty:3,type:"mc",question:"On a map, 1 inch = 25 miles. Two cities are 3.5 inches apart. Actual distance?",choices:["75 mi","82.5 mi","87.5 mi","100 mi"],correctAnswer:2,explanation:"$3.5 \\times 25 = 87.5$ miles.",strategy:"Map problems: multiply map distance by scale factor.",commonMistake:"Dividing by scale factor instead of multiplying."},
{id:"ps-rat-005",topic:"problem-solving",subtopic:"ratios",title:"Ratios & Proportions",difficulty:3,type:"mc",question:"$y$ varies directly with $x$. When $x=4$, $y=12$. What is $y$ when $x=7$?",choices:["15","18","21","28"],correctAnswer:2,explanation:"$y=kx$. $12=4k$, $k=3$. When $x=7$: $y=21$.",strategy:"Direct variation: $y=kx$. Find k first.",commonMistake:"Adding instead of multiplying with the constant."},

// ============================================
// PROBLEM SOLVING - Percentages (7 questions)
// ============================================
{id:"ps-pct-001",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:1,type:"mc",question:"What is 15% of 200?",choices:["15","25","30","35"],correctAnswer:2,explanation:"$0.15 \\times 200 = 30$.",strategy:"Convert % to decimal (divide by 100), then multiply.",commonMistake:"Moving decimal point the wrong direction."},
{id:"ps-pct-002",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:2,type:"mc",question:"$80 shirt, 25% off. Sale price?",choices:["$20","$55","$60","$65"],correctAnswer:2,explanation:"Discount = $80 \\times 0.25 = $20. Sale = $80-$20 = $60.",strategy:"Discount = original x rate. Then subtract.",commonMistake:"Giving discount amount ($20) instead of sale price ($60)."},
{id:"ps-pct-003",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:2,type:"grid-in",question:"40 students passed out of 50 total. What percentage passed?",correctAnswer:80,explanation:"$\\frac{40}{50} \\times 100 = 80\\%$.",strategy:"Percentage = (part/whole) x 100.",commonMistake:"Dividing 50 by 40 instead of 40 by 50."},
{id:"ps-pct-004",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:3,type:"mc",question:"Stock went from $40 to $52. Percent increase?",choices:["12%","23%","30%","52%"],correctAnswer:2,explanation:"Change = $12. Percent = $\\frac{12}{40} \\times 100 = 30\\%$.",strategy:"% change = (change/original) x 100. Divide by ORIGINAL.",commonMistake:"Dividing by new value instead of original."},
{id:"ps-pct-005",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:3,type:"mc",question:"After 20% increase, value is 60. Original value?",choices:["48","50","52","54"],correctAnswer:1,explanation:"$1.20x = 60$, $x = 50$.",strategy:"Increase of p%: new = original x (1 + p/100).",commonMistake:"Computing 20% of 60 and subtracting."},
{id:"ps-pct-006",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:4,type:"mc",question:"Price increases 10% then decreases 10%. Compared to original?",choices:["Same","1% less","1% more","10% less"],correctAnswer:1,explanation:"Start 100. +10%: 110. -10%: $110 \\times 0.9 = 99$. That is 1% less.",strategy:"Successive % changes don't cancel. Multiply the factors.",commonMistake:"Thinking +10% then -10% returns to original."},
{id:"ps-pct-007",topic:"problem-solving",subtopic:"percentages",title:"Percentages",difficulty:2,type:"mc",question:"Meal costs $45. With 20% tip, total paid?",choices:["$9","$36","$54","$65"],correctAnswer:2,explanation:"$45 \\times 1.20 = $54.",strategy:"Total with p% tip = original x (1 + p/100).",commonMistake:"Giving just the tip amount instead of total."},

// ============================================
// PROBLEM SOLVING - Statistics (5 questions)
// ============================================
{id:"ps-stat-001",topic:"problem-solving",subtopic:"statistics",title:"Statistics",difficulty:1,type:"mc",question:"Mean of 4, 8, 12, 16, 20?",choices:["10","12","14","16"],correctAnswer:1,explanation:"Sum = 60. Mean = 60/5 = 12.",strategy:"Mean = sum / count.",commonMistake:"Forgetting to divide by the count."},
{id:"ps-stat-002",topic:"problem-solving",subtopic:"statistics",title:"Statistics",difficulty:2,type:"mc",question:"Median of: 3, 7, 9, 12, 15, 18, 21?",choices:["9","12","15","18"],correctAnswer:1,explanation:"7 numbers, already sorted. Middle (4th) = 12.",strategy:"Median = middle value when sorted.",commonMistake:"Not sorting first, or picking wrong middle."},
{id:"ps-stat-003",topic:"problem-solving",subtopic:"statistics",title:"Statistics",difficulty:2,type:"grid-in",question:"Scores: 70, 75, 80, 85, 90. A 100 is added. New mean? (Round to nearest hundredth)",correctAnswer:83.33,explanation:"New sum = 500. New mean = 500/6 = 83.33.",strategy:"Add new value to sum, divide by new count.",commonMistake:"Dividing by old count (5) instead of new count (6)."},
{id:"ps-stat-004",topic:"problem-solving",subtopic:"statistics",title:"Statistics",difficulty:3,type:"mc",question:"Mean is 50 and median is 45. The data is:",choices:["Skewed right","Skewed left","Symmetric","Cannot determine"],correctAnswer:0,explanation:"Mean > median indicates right (positive) skew.",strategy:"Mean > median = right skew. Mean < median = left skew.",commonMistake:"Confusing left and right skew."},
{id:"ps-stat-005",topic:"problem-solving",subtopic:"statistics",title:"Statistics",difficulty:3,type:"mc",question:"10 numbers have mean 15. If 25 is added, new mean?",choices:["$\\frac{155}{11}$","$\\frac{175}{11}$","$\\frac{160}{11}$","$\\frac{165}{11}$"],correctAnswer:1,explanation:"Original sum = 150. New sum = 175. New mean = 175/11.",strategy:"Sum = mean x count. Then add new value and divide by new count.",commonMistake:"Not computing original sum correctly."},

// ============================================
// PROBLEM SOLVING - Data Interpretation (3 questions)
// ============================================
{id:"ps-di-001",topic:"problem-solving",subtopic:"data-interpretation",title:"Data Interpretation",difficulty:2,type:"mc",question:"200 surveyed: 70 blue, 50 red, 40 green, rest yellow. How many yellow?",choices:["30","35","40","45"],correctAnswer:2,explanation:"$200-70-50-40 = 40$.",strategy:"Categories sum to total: subtract known from total.",commonMistake:"Forgetting one category."},
{id:"ps-di-002",topic:"problem-solving",subtopic:"data-interpretation",title:"Data Interpretation",difficulty:3,type:"mc",question:"60/100 males and 80/120 females exercise regularly. Fraction of ALL people who exercise?",choices:["$\\frac{140}{220}$","$\\frac{60}{100}$","$\\frac{80}{120}$","$\\frac{140}{200}$"],correctAnswer:0,explanation:"Total exercising = 140. Total people = 220. Fraction = 140/220.",strategy:"Add across groups for totals.",commonMistake:"Using only one group's data."},
{id:"ps-di-003",topic:"problem-solving",subtopic:"data-interpretation",title:"Data Interpretation",difficulty:3,type:"mc",question:"Scatterplot shows negative linear trend. Most likely correlation $r$?",choices:["$0.85$","$0.15$","$-0.10$","$-0.82$"],correctAnswer:3,explanation:"Negative trend = negative r. Strong = close to -1. $r=-0.82$.",strategy:"r near 1 = strong positive, near -1 = strong negative, near 0 = weak.",commonMistake:"Thinking strong negative means r near 0."},

// ============================================
// PROBLEM SOLVING - Probability (3 questions)
// ============================================
{id:"ps-prob-001",topic:"problem-solving",subtopic:"probability",title:"Probability",difficulty:1,type:"mc",question:"Bag: 3 red, 5 blue, 2 green. P(blue)?",choices:["$\\frac{1}{5}$","$\\frac{1}{3}$","$\\frac{1}{2}$","$\\frac{3}{5}$"],correctAnswer:2,explanation:"Total = 10. P(blue) = 5/10 = 1/2.",strategy:"P = favorable / total outcomes.",commonMistake:"Not counting ALL marbles for total."},
{id:"ps-prob-002",topic:"problem-solving",subtopic:"probability",title:"Probability",difficulty:2,type:"mc",question:"Fair die rolled. P(even)?",choices:["$\\frac{1}{6}$","$\\frac{1}{3}$","$\\frac{1}{2}$","$\\frac{2}{3}$"],correctAnswer:2,explanation:"Even: 2, 4, 6 = 3 outcomes out of 6. P = 1/2.",strategy:"List favorable outcomes carefully, then divide by total.",commonMistake:"Forgetting one even number."},
{id:"ps-prob-003",topic:"problem-solving",subtopic:"probability",title:"Probability",difficulty:3,type:"grid-in",question:"Class of 30: 18 play soccer, 12 basketball, 5 play both. How many play neither?",correctAnswer:5,explanation:"At least one: $18+12-5=25$. Neither: $30-25=5$.",strategy:"Inclusion-exclusion: |A or B| = |A| + |B| - |A and B|.",commonMistake:"Not subtracting the overlap."},

// ============================================
// GEOMETRY - Area & Perimeter (6 questions)
// ============================================
{id:"geo-ap-001",topic:"geometry",subtopic:"area-perimeter",title:"Area & Perimeter",difficulty:1,type:"mc",question:"Area of rectangle: length 12, width 5?",choices:["17","34","60","120"],correctAnswer:2,explanation:"Area = $12 \\times 5 = 60$.",strategy:"Rectangle: area = lw. Perimeter = 2l+2w.",commonMistake:"Computing perimeter instead of area."},
{id:"geo-ap-002",topic:"geometry",subtopic:"area-perimeter",title:"Area & Perimeter",difficulty:1,type:"mc",question:"Area of triangle: base 10, height 6?",choices:["16","30","60","80"],correctAnswer:1,explanation:"$A = \\frac{1}{2}(10)(6) = 30$.",strategy:"Triangle area = (1/2)bh. Remember the 1/2!",commonMistake:"Forgetting to multiply by 1/2."},
{id:"geo-ap-003",topic:"geometry",subtopic:"area-perimeter",title:"Area & Perimeter",difficulty:2,type:"mc",question:"Area of circle, radius 5? (Use $\\pi \\approx 3.14$)",choices:["15.7","31.4","78.5","157"],correctAnswer:2,explanation:"$A = \\pi r^2 = \\pi(25) = 78.5$.",strategy:"Circle: area = $\\pi r^2$, circumference = $2\\pi r$.",commonMistake:"Using circumference formula instead of area."},
{id:"geo-ap-004",topic:"geometry",subtopic:"area-perimeter",title:"Area & Perimeter",difficulty:2,type:"grid-in",question:"Square has perimeter 48 cm. Area in sq cm?",correctAnswer:144,explanation:"Side = 48/4 = 12. Area = $12^2 = 144$.",strategy:"Square: side = perimeter/4, area = side^2.",commonMistake:"Dividing perimeter by 2 instead of 4."},
{id:"geo-ap-005",topic:"geometry",subtopic:"area-perimeter",title:"Area & Perimeter",difficulty:3,type:"mc",question:"Garden 20x30 ft. Path 2 ft wide surrounds it. Area of path alone?",choices:["208 sq ft","216 sq ft","224 sq ft","240 sq ft"],correctAnswer:1,explanation:"Outer: $24 \\times 34 = 816$. Inner: $600$. Path: $816-600=216$.",strategy:"Path area = outer area - inner area. Add path width to BOTH sides.",commonMistake:"Adding 2 instead of 4 to each dimension."},
{id:"geo-ap-006",topic:"geometry",subtopic:"area-perimeter",title:"Area & Perimeter",difficulty:3,type:"grid-in",question:"Semicircle, diameter 20. Area? (Round to nearest whole, use $\\pi \\approx 3.14$)",correctAnswer:157,explanation:"r=10. Full circle = $314$. Semicircle = $157$.",strategy:"Semicircle = half a circle. Full area / 2.",commonMistake:"Using diameter instead of radius."},

// ============================================
// GEOMETRY - Triangles & Angles (6 questions)
// ============================================
{id:"geo-tri-001",topic:"geometry",subtopic:"triangles",title:"Triangles & Angles",difficulty:1,type:"mc",question:"Two angles are 50 and 60 degrees. Third angle?",choices:["60","70","80","90"],correctAnswer:1,explanation:"$180 - 50 - 60 = 70$.",strategy:"Triangle angles sum to 180.",commonMistake:"Using 360 instead of 180."},
{id:"geo-tri-002",topic:"geometry",subtopic:"triangles",title:"Triangles & Angles",difficulty:2,type:"mc",question:"Right triangle, legs 3 and 4. Hypotenuse?",choices:["5","6","7","$\\sqrt{7}$"],correctAnswer:0,explanation:"$3^2+4^2=25$, $c=5$. Classic 3-4-5 triple!",strategy:"Memorize: 3-4-5, 5-12-13, 8-15-17.",commonMistake:"Adding legs directly (3+4=7)."},
{id:"geo-tri-003",topic:"geometry",subtopic:"triangles",title:"Triangles & Angles",difficulty:2,type:"mc",question:"Hypotenuse 13, one leg 5. Other leg?",choices:["8","10","12","$\\sqrt{194}$"],correctAnswer:2,explanation:"$25+b^2=169$, $b^2=144$, $b=12$. (5-12-13 triple)",strategy:"5-12-13 is another common triple.",commonMistake:"Putting hypotenuse in wrong spot of formula."},
{id:"geo-tri-004",topic:"geometry",subtopic:"triangles",title:"Triangles & Angles",difficulty:3,type:"mc",question:"45-45-90 triangle, leg = 7. Hypotenuse?",choices:["7","$7\\sqrt{2}$","$7\\sqrt{3}$","14"],correctAnswer:1,explanation:"45-45-90 ratio: $1:1:\\sqrt{2}$. Hypotenuse = $7\\sqrt{2}$.",strategy:"45-45-90: hypotenuse = leg x $\\sqrt{2}$.",commonMistake:"Using 30-60-90 ratios instead."},
{id:"geo-tri-005",topic:"geometry",subtopic:"triangles",title:"Triangles & Angles",difficulty:3,type:"mc",question:"30-60-90 triangle, short side = 5. Hypotenuse?",choices:["5","$5\\sqrt{2}$","$5\\sqrt{3}$","10"],correctAnswer:3,explanation:"30-60-90 ratio: $x : x\\sqrt{3} : 2x$. Hypotenuse = $2(5) = 10$.",strategy:"30-60-90: short x 2 = hypotenuse, short x $\\sqrt{3}$ = long leg.",commonMistake:"Confusing which side is opposite which angle."},
{id:"geo-tri-006",topic:"geometry",subtopic:"triangles",title:"Triangles & Angles",difficulty:3,type:"mc",question:"Similar triangles, scale 3:5. Small area = 27 sq cm. Large area?",choices:["45","54","75","108"],correctAnswer:2,explanation:"Area ratio = $(3/5)^2 = 9/25$. $27/A = 9/25$, $A = 75$.",strategy:"Similar figures: area scales by k^2, volume by k^3.",commonMistake:"Using linear scale factor for area instead of squaring."},

// ============================================
// GEOMETRY - Circles (3 questions)
// ============================================
{id:"geo-cir-001",topic:"geometry",subtopic:"circles",title:"Circles",difficulty:2,type:"mc",question:"Circle radius 8. Circumference?",choices:["$8\\pi$","$16\\pi$","$32\\pi$","$64\\pi$"],correctAnswer:1,explanation:"$C = 2\\pi r = 16\\pi$.",strategy:"C = $2\\pi r$ or $\\pi d$.",commonMistake:"Using area formula instead."},
{id:"geo-cir-002",topic:"geometry",subtopic:"circles",title:"Circles",difficulty:3,type:"mc",question:"Sector: radius 6, central angle 60. Area?",choices:["$6\\pi$","$12\\pi$","$18\\pi$","$36\\pi$"],correctAnswer:0,explanation:"$\\frac{60}{360} \\times \\pi(36) = \\frac{1}{6}(36\\pi) = 6\\pi$.",strategy:"Sector area = (angle/360) x full circle area.",commonMistake:"Forgetting to take the fraction of the circle."},
{id:"geo-cir-003",topic:"geometry",subtopic:"circles",title:"Circles",difficulty:3,type:"mc",question:"$(x-2)^2+(y+3)^2=25$. Center and radius?",choices:["$(2,-3)$, r=5","$(-2,3)$, r=5","$(2,3)$, r=25","$(2,-3)$, r=25"],correctAnswer:0,explanation:"$(x-h)^2+(y-k)^2=r^2$. Center=(2,-3), r=5.",strategy:"Signs are opposite in the formula! $(y+3) = (y-(-3))$ so k=-3.",commonMistake:"Getting signs wrong, or giving r^2 instead of r."},

// ============================================
// GEOMETRY - Volume (3 questions)
// ============================================
{id:"geo-vol-001",topic:"geometry",subtopic:"volume",title:"Volume",difficulty:2,type:"mc",question:"Rectangular box 4 x 5 x 6. Volume?",choices:["15","60","120","240"],correctAnswer:2,explanation:"$V = 4 \\times 5 \\times 6 = 120$.",strategy:"Box volume = lwh.",commonMistake:"Computing surface area instead."},
{id:"geo-vol-002",topic:"geometry",subtopic:"volume",title:"Volume",difficulty:2,type:"mc",question:"Cylinder: radius 3, height 10. Volume?",choices:["$30\\pi$","$60\\pi$","$90\\pi$","$180\\pi$"],correctAnswer:2,explanation:"$V = \\pi r^2 h = \\pi(9)(10) = 90\\pi$.",strategy:"Cylinder = circle area x height = $\\pi r^2 h$.",commonMistake:"Using $2\\pi r$ instead of $\\pi r^2$ for the base."},
{id:"geo-vol-003",topic:"geometry",subtopic:"volume",title:"Volume",difficulty:3,type:"mc",question:"Cone: radius 3, height 12. Volume?",choices:["$12\\pi$","$36\\pi$","$108\\pi$","$324\\pi$"],correctAnswer:1,explanation:"$V = \\frac{1}{3}\\pi r^2 h = \\frac{1}{3}\\pi(9)(12) = 36\\pi$.",strategy:"Cone = (1/3) cylinder = $(1/3)\\pi r^2 h$.",commonMistake:"Forgetting the 1/3 factor."},

// ============================================
// GEOMETRY - Trigonometry (3 questions)
// ============================================
{id:"geo-trig-001",topic:"geometry",subtopic:"trigonometry",title:"Trigonometry",difficulty:3,type:"mc",question:"Right triangle: opposite = 3, hypotenuse = 5. $\\sin(A)$?",choices:["$\\frac{3}{5}$","$\\frac{4}{5}$","$\\frac{3}{4}$","$\\frac{5}{3}$"],correctAnswer:0,explanation:"$\\sin = \\frac{\\text{opposite}}{\\text{hypotenuse}} = \\frac{3}{5}$.",strategy:"SOH CAH TOA: Sin=O/H, Cos=A/H, Tan=O/A.",commonMistake:"Confusing which sides go where."},
{id:"geo-trig-002",topic:"geometry",subtopic:"trigonometry",title:"Trigonometry",difficulty:3,type:"mc",question:"$\\tan(B) = 5/12$, opposite = 5. Hypotenuse?",choices:["12","13","14","17"],correctAnswer:1,explanation:"Adjacent = 12. Hypotenuse = $\\sqrt{25+144} = \\sqrt{169} = 13$.",strategy:"If you know two sides, Pythagorean theorem gives the third.",commonMistake:"Adding 5+12=17 instead of using Pythagorean theorem."},
{id:"geo-trig-003",topic:"geometry",subtopic:"trigonometry",title:"Trigonometry",difficulty:4,type:"mc",question:"Angle of elevation 30 degrees from 100 ft away. Building height?",choices:["50 ft","57.7 ft","86.6 ft","100 ft"],correctAnswer:1,explanation:"$\\tan(30°)=h/100$. $h=100/\\sqrt{3} \\approx 57.7$ ft.",strategy:"Draw a picture! Elevation problems use right triangle trig.",commonMistake:"Using sin or cos when adjacent is given (use tan)."}
];
